# What

> Análise de dois datasets:
> Enem por Escolas: dados sobre o desempenho de cada escola no ENEM 
> censo escolar 2015: dados sobre a infraestrutura das escolas

>O objetivo será analisar a relação entre essas duas bases, entendendo como fatores socioeconomicos afetam o desempenho no ENEM, explorando também possíveis relações regionais

# Why

> Dado que o enem é o ponto de entrada no ensino superior, é extremamente importante entender a influência de fatores socioeconomicos e estruturais e como isso pode afetar o acesso a educação

# How

> será realizada uma analise explorátoria nos dados separadamente, depois uma analise conjunta comparando as duas tabelas

# Imports

In [2]:
import pandas as pd

# Analise Exploratória

> carregando as tabelas

In [35]:
df_enem_escola = pd.read_csv('microdados_enem_por_escola/DADOS/MICRODADOS_ENEM_ESCOLA.csv', encoding='ISO-8859-1', sep=';')
df_enem_escola.head()
df_censo = pd.read_csv('microdados_ed_basica_2015/dados/microdados_ed_basica_2015.csv', encoding='ISO-8859-1', sep=';')

/var/folders/xy/xqxsj6796gl11wpqz6hp11sr0000gn/T/ipykernel_21349/1856550647.py:1: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  df_enem_escola = pd.read_csv('microdados_enem_por_escola/DADOS/MICRODADOS_ENEM_ESCOLA.csv', encoding='ISO-8859-1', sep=';')
/var/folders/xy/xqxsj6796gl11wpqz6hp11sr0000gn/T/ipykernel_21349/1856550647.py:3: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  df_censo = pd.read_csv('microdados_ed_basica_2015/dados/microdados_ed_basica_2015.csv', encoding='ISO-8859-1', sep=';')


## Enem Por Escolas - Análise Inicial

> Sao 27 colunas:
> - 24 numéricas (8 int e 14 float)
> - 8 categóricas

> Inicialmente temos 172,305 linhas contendo informações de 2005 a 2015  
> - Primeiras 10 colunas são informações relacionadas a escola, como nome, uf, municipio e etc  
> - Colunas 11 a 20 são informações sobre participação no enem, media de nota por area do conhecimento, taxa de participação  
> - Coluna 21 é o indice socioeconomico  
> - Coluna 22 é referente ao nivel de formação do corpo docente  
> - Colunas 23 a 26 são informações referentes ao desempenho, permanencia, aprovação, reprovação, abandono  
> - Coluna 27 é o porte da escola

In [5]:
df_enem_escola.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172305 entries, 0 to 172304
Data columns (total 27 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   NU_ANO                     172305 non-null  int64  
 1   CO_UF_ESCOLA               172305 non-null  int64  
 2   SG_UF_ESCOLA               172305 non-null  object 
 3   CO_MUNICIPIO_ESCOLA        172305 non-null  int64  
 4   NO_MUNICIPIO_ESCOLA        172305 non-null  object 
 5   CO_ESCOLA_EDUCACENSO       172305 non-null  int64  
 6   NO_ESCOLA_EDUCACENSO       172305 non-null  object 
 7   TP_DEPENDENCIA_ADM_ESCOLA  172305 non-null  int64  
 8   TP_LOCALIZACAO_ESCOLA      172305 non-null  int64  
 9   NU_MATRICULAS              172305 non-null  int64  
 10  NU_PARTICIPANTES_NEC_ESP   45355 non-null   float64
 11  NU_PARTICIPANTES           172305 non-null  int64  
 12  NU_TAXA_PARTICIPACAO       104687 non-null  float64
 13  NU_MEDIA_CN                10

In [6]:
df_enem_escola.head()

NU_ANO  CO_UF_ESCOLA SG_UF_ESCOLA  CO_MUNICIPIO_ESCOLA NO_MUNICIPIO_ESCOLA  \
0    2007            11           RO              1100205         Porto Velho   
1    2006            11           RO              1100205         Porto Velho   
2    2005            11           RO              1100205         Porto Velho   
3    2008            11           RO              1100205         Porto Velho   
4    2007            11           RO              1100205         Porto Velho   

   CO_ESCOLA_EDUCACENSO       NO_ESCOLA_EDUCACENSO  TP_DEPENDENCIA_ADM_ESCOLA  \
0              11000058  CENTRO DE ENSINO CLASSE A                          4   
1              11000058  CENTRO DE ENSINO CLASSE A                          4   
2              11000058  CENTRO DE ENSINO CLASSE A                          4   
3              11000058  CENTRO DE ENSINO CLASSE A                          4   
4              11000171  CENTRO EDUCACIONAL MOJUCA                          4   

   TP_LOCALIZACAO_ESCOLA  NU_MATRICULAS  ...  NU_MEDIA_RED  NU_MEDIA_OBJ  \
0                      1            144  ...           NaN           NaN   
1                      1            184  ...           NaN           NaN   
2                      1            220  ...           NaN           NaN   
3                      1            186  ...         72.16         60.02   
4                      1             19  ...           NaN           NaN   

   NU_MEDIA_TOT  INSE  PC_FORMACAO_DOCENTE  NU_TAXA_PERMANENCIA  \
0         69.03   NaN                  NaN                  NaN   
1         57.82   NaN                  NaN                  NaN   
2         64.83   NaN                  NaN                  NaN   
3           NaN   NaN                  NaN                  NaN   
4         58.84   NaN                  NaN                  NaN   

   NU_TAXA_APROVACAO  NU_TAXA_REPROVACAO  NU_TAXA_ABANDONO  \
0               91.9                 8.1               0.0   
1                NaN                 NaN               NaN   
2               86.5                12.4               1.1   
3               90.3                 9.7               0.0   
4               74.2                21.0               4.8   

          PORTE_ESCOLA  
0  Maior que 90 alunos  
1  Maior que 90 alunos  
2  Maior que 90 alunos  
3  Maior que 90 alunos  
4     De 1 a 30 alunos  

[5 rows x 27 columns]

> Como iremos analisar o censo de 2015 o primeiro processamento será filtrar a tabela para pegar apenas os dados de 2015  
> Com isso ficamos com um total de 15,598 linhas

In [16]:
df_enem_escola_2015 = df_enem_escola.loc[df_enem_escola['NU_ANO'] == 2015]
df_enem_escola_2015.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15598 entries, 67619 to 172304
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   NU_ANO                     15598 non-null  int64  
 1   CO_UF_ESCOLA               15598 non-null  int64  
 2   SG_UF_ESCOLA               15598 non-null  object 
 3   CO_MUNICIPIO_ESCOLA        15598 non-null  int64  
 4   NO_MUNICIPIO_ESCOLA        15598 non-null  object 
 5   CO_ESCOLA_EDUCACENSO       15598 non-null  int64  
 6   NO_ESCOLA_EDUCACENSO       15598 non-null  object 
 7   TP_DEPENDENCIA_ADM_ESCOLA  15598 non-null  int64  
 8   TP_LOCALIZACAO_ESCOLA      15598 non-null  int64  
 9   NU_MATRICULAS              15598 non-null  int64  
 10  NU_PARTICIPANTES_NEC_ESP   15598 non-null  float64
 11  NU_PARTICIPANTES           15598 non-null  int64  
 12  NU_TAXA_PARTICIPACAO       15598 non-null  float64
 13  NU_MEDIA_CN                15598 non-null  flo

In [12]:
df_enem_escola_2015.head()

NU_ANO  CO_UF_ESCOLA SG_UF_ESCOLA  CO_MUNICIPIO_ESCOLA  \
67619    2015            11           RO              1100205   
67628    2015            11           RO              1100205   
67640    2015            11           RO              1100205   
67642    2015            11           RO              1100205   
67648    2015            11           RO              1100205   

      NO_MUNICIPIO_ESCOLA  CO_ESCOLA_EDUCACENSO  \
67619         Porto Velho              11000058   
67628         Porto Velho              11000171   
67640         Porto Velho              11000198   
67642         Porto Velho              11000244   
67648         Porto Velho              11000252   

                                    NO_ESCOLA_EDUCACENSO  \
67619                          CENTRO DE ENSINO CLASSE A   
67628                          CENTRO EDUCACIONAL MOJUCA   
67640                        CENTRO EDUCACIONAL OBJETIVO   
67642                                  COLEGIO DOM BOSCO   
67648  CENTRO EDUCACIONAL OBJETIVO - UNIDADE JARDIM A...   

       TP_DEPENDENCIA_ADM_ESCOLA  TP_LOCALIZACAO_ESCOLA  NU_MATRICULAS  ...  \
67619                          4                      1            137  ...   
67628                          4                      1             20  ...   
67640                          4                      1             39  ...   
67642                          4                      1             55  ...   
67648                          4                      1             26  ...   

       NU_MEDIA_RED  NU_MEDIA_OBJ  NU_MEDIA_TOT     INSE  PC_FORMACAO_DOCENTE  \
67619        732.00           NaN           NaN  Grupo 6                 67.5   
67628        507.82           NaN           NaN  Grupo 4                 58.3   
67640        652.43           NaN           NaN  Grupo 5                 67.7   
67642        591.84           NaN           NaN  Grupo 5                 56.0   
67648        583.48           NaN           NaN  Grupo 5                 72.7   

       NU_TAXA_PERMANENCIA  NU_TAXA_APROVACAO  NU_TAXA_REPROVACAO  \
67619                78.46               96.1                 3.9   
67628                70.59               94.6                 5.4   
67640                40.54               90.1                 9.9   
67642                81.63               88.7                10.5   
67648                52.17               84.5                13.1   

       NU_TAXA_ABANDONO         PORTE_ESCOLA  
67619               0.0  Maior que 90 alunos  
67628               0.0     De 1 a 30 alunos  
67640               0.0    De 31 a 60 alunos  
67642               0.8    De 31 a 60 alunos  
67648               2.4     De 1 a 30 alunos  

[5 rows x 27 columns]

> Primero passo é verificar se há dados faltantes  
> A média da parte objetiva e total vieram vazias em todas as linhas — mas esses valores podem ser calculados  
> A coluna PC_FORMACAO_DOCENTE tem 19 dados faltantes  
> As colunas NU_TAXA_APROVACAO, NU_TAXA_REPROVACAO, NU_TAXA_ABANDONO tem 82 dados faltantes 

In [18]:
df_enem_escola_2015.isnull().sum()

NU_ANO                           0
CO_UF_ESCOLA                     0
SG_UF_ESCOLA                     0
CO_MUNICIPIO_ESCOLA              0
NO_MUNICIPIO_ESCOLA              0
CO_ESCOLA_EDUCACENSO             0
NO_ESCOLA_EDUCACENSO             0
TP_DEPENDENCIA_ADM_ESCOLA        0
TP_LOCALIZACAO_ESCOLA            0
NU_MATRICULAS                    0
NU_PARTICIPANTES_NEC_ESP         0
NU_PARTICIPANTES                 0
NU_TAXA_PARTICIPACAO             0
NU_MEDIA_CN                      0
NU_MEDIA_CH                      0
NU_MEDIA_LP                      0
NU_MEDIA_MT                      0
NU_MEDIA_RED                     0
NU_MEDIA_OBJ                 15598
NU_MEDIA_TOT                 15598
INSE                             1
PC_FORMACAO_DOCENTE             19
NU_TAXA_PERMANENCIA              0
NU_TAXA_APROVACAO               82
NU_TAXA_REPROVACAO              82
NU_TAXA_ABANDONO                82
PORTE_ESCOLA                     0
dtype: int64

> como esse número representa uma porcentagem bem pequena da quantidade total, optamos por excluir as linhas que contem dados faltantes  
> ficamos então com um total de 15,497 linhas

In [27]:
df_enem_escola_2015 = df_enem_escola_2015.dropna(subset=['NU_TAXA_APROVACAO', 'PC_FORMACAO_DOCENTE', 'INSE'])
df_enem_escola_2015.shape

(15497, 27)

> completando a coluda de media objetiva e média total

In [33]:
df_enem_escola_2015['NU_MEDIA_OBJ'] = df_enem_escola_2015[
    ['NU_MEDIA_CH', 'NU_MEDIA_CN', 'NU_MEDIA_LP', 'NU_MEDIA_MT']
].mean(axis=1)

df_enem_escola_2015['NU_MEDIA_TOT'] = df_enem_escola_2015[
    ['NU_MEDIA_OBJ', 'NU_MEDIA_RED']
].mean(axis=1)


In [34]:
df_enem_escola_2015.describe()


NU_ANO  CO_UF_ESCOLA  CO_MUNICIPIO_ESCOLA  CO_ESCOLA_EDUCACENSO  \
count  15497.0  15497.000000         1.549700e+04          1.549700e+04   
mean    2015.0     33.145641         3.331123e+06          3.327631e+07   
std        0.0      9.275797         9.290573e+05          9.264129e+06   
min     2015.0     11.000000         1.100015e+06          1.100006e+07   
25%     2015.0     27.000000         2.704302e+06          2.704076e+07   
50%     2015.0     33.000000         3.304557e+06          3.309027e+07   
75%     2015.0     35.000000         3.557105e+06          3.592583e+07   
max     2015.0     53.000000         5.300108e+06          5.308200e+07   

       TP_DEPENDENCIA_ADM_ESCOLA  TP_LOCALIZACAO_ESCOLA  NU_MATRICULAS  \
count               15497.000000           15497.000000   15497.000000   
mean                    2.792992               1.036136      85.693554   
std                     1.005211               0.186635      84.033039   
min                     1.000000               1.000000      10.000000   
25%                     2.000000               1.000000      29.000000   
50%                     2.000000               1.000000      58.000000   
75%                     4.000000               1.000000     112.000000   
max                     4.000000               2.000000     842.000000   

       NU_PARTICIPANTES_NEC_ESP  NU_PARTICIPANTES  NU_TAXA_PARTICIPACAO  ...  \
count              15497.000000      15497.000000          15497.000000  ...   
mean                   0.556430         62.671678             76.106306  ...   
std                    1.329321         61.989427             15.386659  ...   
min                    0.000000         10.000000             50.000000  ...   
25%                    0.000000         23.000000             62.160000  ...   
50%                    0.000000         42.000000             76.920000  ...   
75%                    1.000000         80.000000             90.320000  ...   
max                   27.000000        716.000000            100.000000  ...   

        NU_MEDIA_LP   NU_MEDIA_MT  NU_MEDIA_RED  NU_MEDIA_OBJ  NU_MEDIA_TOT  \
count  15497.000000  15497.000000  15497.000000  15497.000000  15497.000000   
mean     515.229822    492.495558    563.582697    516.300888    539.941792   
std       41.905099     69.103568     77.925528     48.417537     61.642956   
min      397.090000    372.450000    345.000000    413.157500    385.460000   
25%      483.990000    442.710000    508.000000    480.502500    494.840000   
50%      509.460000    471.250000    546.620000    503.425000    524.397500   
75%      545.630000    528.140000    609.450000    546.462500    577.825000   
max      681.230000    873.650000    930.000000    751.287500    807.622500   

       PC_FORMACAO_DOCENTE  NU_TAXA_PERMANENCIA  NU_TAXA_APROVACAO  \
count         15497.000000         15497.000000       15497.000000   
mean             60.422630            76.443371          87.406285   
std              17.192164            50.100925          10.955223   
min               0.000000             0.000000           0.000000   
25%              49.700000            69.230000          80.800000   
50%              61.900000            80.430000          90.500000   
75%              73.000000            88.890000          96.200000   
max             100.000000          5822.000000         100.000000   

       NU_TAXA_REPROVACAO  NU_TAXA_ABANDONO  
count        15497.000000      15497.000000  
mean             8.803504          3.790211  
std              7.917636          5.559721  
min              0.000000          0.000000  
25%              2.800000          0.000000  
50%              6.700000          0.900000  
75%             12.700000          6.000000  
max             60.200000         85.700000  

[8 rows x 22 columns]

## Censo 2015 — Análise Inicial

> São 370 colunas  
> 354 são numéricas (2 float e 352 int)  
> 16 são categóricas  
> 237,878 linhas

In [36]:
df_censo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237879 entries, 0 to 237878
Columns: 370 entries, NU_ANO_CENSO to QT_TUR_ESP_CE
dtypes: float64(2), int64(352), object(16)
memory usage: 671.5+ MB


> - Colunas 1 a 13 são informações sobre a localização da Escola como UF, Municipio, Regiao e etc  
> - 14 a 273 são informações gerais sobre a Escola e todos os dados sobre infraestrutura  
> - 274 a 370 são informações sobre numero de Matriculas e Docentes, incluindo oferta de matricula, numero de matriculas por etapa do ensino, genero, docentes por etapa e etc

In [46]:
list(df_censo.columns)

['NU_ANO_CENSO',
 'NO_REGIAO',
 'CO_REGIAO',
 'NO_UF',
 'SG_UF',
 'CO_UF',
 'NO_MUNICIPIO',
 'CO_MUNICIPIO',
 'NO_MESORREGIAO',
 'CO_MESORREGIAO',
 'NO_MICRORREGIAO',
 'CO_MICRORREGIAO',
 'CO_DISTRITO',
 'CO_ENTIDADE',
 'NO_ENTIDADE',
 'TP_DEPENDENCIA',
 'TP_CATEGORIA_ESCOLA_PRIVADA',
 'TP_LOCALIZACAO',
 'TP_LOCALIZACAO_DIFERENCIADA',
 'DS_ENDERECO',
 'NU_ENDERECO',
 'DS_COMPLEMENTO',
 'NO_BAIRRO',
 'CO_CEP',
 'NU_DDD',
 'NU_TELEFONE',
 'TP_SITUACAO_FUNCIONAMENTO',
 'CO_ORGAO_REGIONAL',
 'DT_ANO_LETIVO_INICIO',
 'DT_ANO_LETIVO_TERMINO',
 'IN_VINCULO_SECRETARIA_EDUCACAO',
 'IN_VINCULO_SEGURANCA_PUBLICA',
 'IN_VINCULO_SECRETARIA_SAUDE',
 'IN_VINCULO_OUTRO_ORGAO',
 'IN_CONVENIADA_PP',
 'TP_CONVENIO_PODER_PUBLICO',
 'IN_MANT_ESCOLA_PRIVADA_EMP',
 'IN_MANT_ESCOLA_PRIVADA_ONG',
 'IN_MANT_ESCOLA_PRIVADA_OSCIP',
 'IN_MANT_ESCOLA_PRIV_ONG_OSCIP',
 'IN_MANT_ESCOLA_PRIVADA_SIND',
 'IN_MANT_ESCOLA_PRIVADA_SIST_S',
 'IN_MANT_ESCOLA_PRIVADA_S_FINS',
 'NU_CNPJ_ESCOLA_PRIVADA',
 'NU_CNPJ_MANTENEDORA',

In [50]:
df_censo.head()

NU_ANO_CENSO NO_REGIAO  CO_REGIAO     NO_UF SG_UF  CO_UF           NO_MUNICIPIO  CO_MUNICIPIO     NO_MESORREGIAO  CO_MESORREGIAO NO_MICRORREGIAO  CO_MICRORREGIAO  CO_DISTRITO  CO_ENTIDADE                             NO_ENTIDADE  TP_DEPENDENCIA  TP_CATEGORIA_ESCOLA_PRIVADA  TP_LOCALIZACAO  TP_LOCALIZACAO_DIFERENCIADA        DS_ENDERECO NU_ENDERECO DS_COMPLEMENTO         NO_BAIRRO    CO_CEP NU_DDD NU_TELEFONE  TP_SITUACAO_FUNCIONAMENTO CO_ORGAO_REGIONAL DT_ANO_LETIVO_INICIO DT_ANO_LETIVO_TERMINO  IN_VINCULO_SECRETARIA_EDUCACAO  IN_VINCULO_SEGURANCA_PUBLICA  IN_VINCULO_SECRETARIA_SAUDE  IN_VINCULO_OUTRO_ORGAO  IN_CONVENIADA_PP  TP_CONVENIO_PODER_PUBLICO  IN_MANT_ESCOLA_PRIVADA_EMP  IN_MANT_ESCOLA_PRIVADA_ONG  IN_MANT_ESCOLA_PRIVADA_OSCIP  IN_MANT_ESCOLA_PRIV_ONG_OSCIP  IN_MANT_ESCOLA_PRIVADA_SIND  IN_MANT_ESCOLA_PRIVADA_SIST_S  IN_MANT_ESCOLA_PRIVADA_S_FINS  NU_CNPJ_ESCOLA_PRIVADA  NU_CNPJ_MANTENEDORA  TP_REGULAMENTACAO  TP_RESPONSAVEL_REGULAMENTACAO  CO_ESCOLA_SEDE_VINCULADA  CO_IES_OFERTANTE  IN_LOCAL_FUNC_PREDIO_ESCOLAR  TP_OCUPACAO_PREDIO_ESCOLAR  IN_LOCAL_FUNC_SALAS_EMPRESA  IN_LOCAL_FUNC_SOCIOEDUCATIVO  IN_LOCAL_FUNC_UNID_PRISIONAL  IN_LOCAL_FUNC_PRISIONAL_SOCIO  IN_LOCAL_FUNC_TEMPLO_IGREJA  IN_LOCAL_FUNC_CASA_PROFESSOR  IN_LOCAL_FUNC_GALPAO  TP_OCUPACAO_GALPAO  IN_LOCAL_FUNC_SALAS_OUTRA_ESC  IN_LOCAL_FUNC_OUTROS  IN_PREDIO_COMPARTILHADO  IN_AGUA_FILTRADA  IN_AGUA_POTAVEL  IN_AGUA_REDE_PUBLICA  IN_AGUA_POCO_ARTESIANO  IN_AGUA_CACIMBA  IN_AGUA_FONTE_RIO  IN_AGUA_INEXISTENTE  IN_ENERGIA_REDE_PUBLICA  IN_ENERGIA_GERADOR  IN_ENERGIA_GERADOR_FOSSIL  IN_ENERGIA_OUTROS  IN_ENERGIA_RENOVAVEL  IN_ENERGIA_INEXISTENTE  IN_ESGOTO_REDE_PUBLICA  IN_ESGOTO_FOSSA_SEPTICA  IN_ESGOTO_FOSSA_COMUM  IN_ESGOTO_FOSSA  IN_ESGOTO_INEXISTENTE  IN_LIXO_SERVICO_COLETA  IN_LIXO_QUEIMA  IN_LIXO_ENTERRA  IN_LIXO_DESTINO_FINAL_PUBLICO  IN_LIXO_DESCARTA_OUTRA_AREA  IN_LIXO_JOGA_OUTRA_AREA  IN_LIXO_OUTROS  IN_LIXO_RECICLA  IN_TRATAMENTO_LIXO_SEPARACAO  IN_TRATAMENTO_LIXO_REUTILIZA  IN_TRATAMENTO_LIXO_RECICLAGEM  IN_TRATAMENTO_LIXO_INEXISTENTE  IN_ALMOXARIFADO  IN_AREA_VERDE  IN_AUDITORIO  IN_BANHEIRO_FORA_PREDIO  IN_BANHEIRO_DENTRO_PREDIO  IN_BANHEIRO  IN_BANHEIRO_EI  IN_BANHEIRO_PNE  IN_BANHEIRO_FUNCIONARIOS  IN_BANHEIRO_CHUVEIRO  IN_BERCARIO  IN_BIBLIOTECA  IN_BIBLIOTECA_SALA_LEITURA  IN_COZINHA  IN_DESPENSA  IN_DORMITORIO_ALUNO  IN_DORMITORIO_PROFESSOR  IN_LABORATORIO_CIENCIAS  IN_LABORATORIO_INFORMATICA  IN_PATIO_COBERTO  IN_PATIO_DESCOBERTO  IN_PARQUE_INFANTIL  IN_PISCINA  IN_QUADRA_ESPORTES  IN_QUADRA_ESPORTES_COBERTA  IN_QUADRA_ESPORTES_DESCOBERTA  IN_REFEITORIO  IN_SALA_ATELIE_ARTES  IN_SALA_MUSICA_CORAL  IN_SALA_ESTUDIO_DANCA  IN_SALA_MULTIUSO  IN_SALA_DIRETORIA  IN_SALA_LEITURA  IN_SALA_PROFESSOR  IN_SALA_REPOUSO_ALUNO  IN_SECRETARIA  IN_SALA_ATENDIMENTO_ESPECIAL  IN_TERREIRAO  IN_VIVEIRO  IN_DEPENDENCIAS_PNE  IN_LAVANDERIA  IN_DEPENDENCIAS_OUTRAS  IN_ACESSIBILIDADE_CORRIMAO  IN_ACESSIBILIDADE_ELEVADOR  IN_ACESSIBILIDADE_PISOS_TATEIS  IN_ACESSIBILIDADE_VAO_LIVRE  IN_ACESSIBILIDADE_RAMPAS  IN_ACESSIBILIDADE_SINAL_SONORO  IN_ACESSIBILIDADE_SINAL_TATIL  IN_ACESSIBILIDADE_SINAL_VISUAL  IN_ACESSIBILIDADE_INEXISTENTE  QT_SALAS_EXISTENTES  QT_SALAS_UTILIZADAS_DENTRO  QT_SALAS_UTILIZADAS_FORA  QT_SALAS_UTILIZADAS  QT_SALAS_UTILIZA_CLIMATIZADAS  QT_SALAS_UTILIZADAS_ACESSIVEIS  IN_EQUIP_PARABOLICA  IN_COMPUTADOR  IN_EQUIP_COPIADORA  IN_EQUIP_IMPRESSORA  IN_EQUIP_IMPRESSORA_MULT  IN_EQUIP_SCANNER  IN_EQUIP_NENHUM  IN_EQUIP_DVD  QT_EQUIP_DVD  IN_EQUIP_SOM  QT_EQUIP_SOM  IN_EQUIP_TV  QT_EQUIP_TV  IN_EQUIP_LOUSA_DIGITAL  QT_EQUIP_LOUSA_DIGITAL  IN_EQUIP_MULTIMIDIA  QT_EQUIP_MULTIMIDIA  IN_EQUIP_VIDEOCASSETE  IN_EQUIP_RETROPROJETOR  IN_EQUIP_FAX  IN_EQUIP_FOTO  QT_EQUIP_VIDEOCASSETE  QT_EQUIP_PARABOLICA  QT_EQUIP_COPIADORA  QT_EQUIP_RETROPROJETOR  QT_EQUIP_IMPRESSORA  QT_EQUIP_IMPRESSORA_MULT  QT_EQUIP_FAX  QT_EQUIP_FOTO  QT_COMP_ALUNO  IN_DESKTOP_ALUNO  QT_DESKTOP_ALUNO  IN_COMP_PORTATIL_ALUNO  QT_COMP_PORTATIL_ALUNO  IN_TABLET_ALUNO  QT_TABLET_ALUNO  QT_COMPUT

> o primeiro filtro será pegar os dados apenas de escolas que estão na tabela de 'enem por escolas'   
> assim, ficamos com 15,497 linhas nessa tabela também

In [51]:
df_censo = df_censo[df_censo['CO_ENTIDADE'].isin(df_enem_escola_2015['CO_ESCOLA_EDUCACENSO'])]
df_censo.shape

(15497, 370)

> proximo passo é verificar valores nulos
> - 984 em NU_ENDERECO
> - 13,452 em DS_COMPLEMENTO
> - 206 em 206
> - 727 em CO_ORGAO_REGIONAL
> - 9,251 em NU_CNPJ_ESCOLA_PRIVADA
> - 9,251 em NU_CNPJ_MANTENEDORA

In [52]:
df_censo.isna().sum()

NU_ANO_CENSO                          0
NO_REGIAO                             0
CO_REGIAO                             0
NO_UF                                 0
SG_UF                                 0
CO_UF                                 0
NO_MUNICIPIO                          0
CO_MUNICIPIO                          0
NO_MESORREGIAO                        0
CO_MESORREGIAO                        0
NO_MICRORREGIAO                       0
CO_MICRORREGIAO                       0
CO_DISTRITO                           0
CO_ENTIDADE                           0
NO_ENTIDADE                           0
TP_DEPENDENCIA                        0
TP_CATEGORIA_ESCOLA_PRIVADA           0
TP_LOCALIZACAO                        0
TP_LOCALIZACAO_DIFERENCIADA           0
DS_ENDERECO                           0
NU_ENDERECO                         984
DS_COMPLEMENTO                    13452
NO_BAIRRO                           206
CO_CEP                                0
NU_DDD                                0


> avaliamos que nenhuma dessas colunas seria revante para a nossa analise, então optamos por excluir elas já que elas tem uma quantidade grande de dados faltando

In [55]:
columns_to_drop = ['NU_ENDERECO', 'DS_COMPLEMENTO', 'CO_ORGAO_REGIONAL', 'NU_CNPJ_ESCOLA_PRIVADA', 'NU_CNPJ_MANTENEDORA']
df_censo.drop(axis=1,columns=columns_to_drop)

NU_ANO_CENSO     NO_REGIAO  CO_REGIAO             NO_UF SG_UF  CO_UF           NO_MUNICIPIO  CO_MUNICIPIO     NO_MESORREGIAO  CO_MESORREGIAO NO_MICRORREGIAO  CO_MICRORREGIAO  CO_DISTRITO  CO_ENTIDADE                             NO_ENTIDADE  TP_DEPENDENCIA  TP_CATEGORIA_ESCOLA_PRIVADA  TP_LOCALIZACAO  TP_LOCALIZACAO_DIFERENCIADA                   DS_ENDERECO             NO_BAIRRO    CO_CEP NU_DDD NU_TELEFONE  TP_SITUACAO_FUNCIONAMENTO DT_ANO_LETIVO_INICIO DT_ANO_LETIVO_TERMINO  IN_VINCULO_SECRETARIA_EDUCACAO  IN_VINCULO_SEGURANCA_PUBLICA  IN_VINCULO_SECRETARIA_SAUDE  IN_VINCULO_OUTRO_ORGAO  IN_CONVENIADA_PP  TP_CONVENIO_PODER_PUBLICO  IN_MANT_ESCOLA_PRIVADA_EMP  IN_MANT_ESCOLA_PRIVADA_ONG  IN_MANT_ESCOLA_PRIVADA_OSCIP  IN_MANT_ESCOLA_PRIV_ONG_OSCIP  IN_MANT_ESCOLA_PRIVADA_SIND  IN_MANT_ESCOLA_PRIVADA_SIST_S  IN_MANT_ESCOLA_PRIVADA_S_FINS  TP_REGULAMENTACAO  TP_RESPONSAVEL_REGULAMENTACAO  CO_ESCOLA_SEDE_VINCULADA  CO_IES_OFERTANTE  IN_LOCAL_FUNC_PREDIO_ESCOLAR  TP_OCUPACAO_PREDIO_ESCOLAR  IN_LOCAL_FUNC_SALAS_EMPRESA  IN_LOCAL_FUNC_SOCIOEDUCATIVO  IN_LOCAL_FUNC_UNID_PRISIONAL  IN_LOCAL_FUNC_PRISIONAL_SOCIO  IN_LOCAL_FUNC_TEMPLO_IGREJA  IN_LOCAL_FUNC_CASA_PROFESSOR  IN_LOCAL_FUNC_GALPAO  TP_OCUPACAO_GALPAO  IN_LOCAL_FUNC_SALAS_OUTRA_ESC  IN_LOCAL_FUNC_OUTROS  IN_PREDIO_COMPARTILHADO  IN_AGUA_FILTRADA  IN_AGUA_POTAVEL  IN_AGUA_REDE_PUBLICA  IN_AGUA_POCO_ARTESIANO  IN_AGUA_CACIMBA  IN_AGUA_FONTE_RIO  IN_AGUA_INEXISTENTE  IN_ENERGIA_REDE_PUBLICA  IN_ENERGIA_GERADOR  IN_ENERGIA_GERADOR_FOSSIL  IN_ENERGIA_OUTROS  IN_ENERGIA_RENOVAVEL  IN_ENERGIA_INEXISTENTE  IN_ESGOTO_REDE_PUBLICA  IN_ESGOTO_FOSSA_SEPTICA  IN_ESGOTO_FOSSA_COMUM  IN_ESGOTO_FOSSA  IN_ESGOTO_INEXISTENTE  IN_LIXO_SERVICO_COLETA  IN_LIXO_QUEIMA  IN_LIXO_ENTERRA  IN_LIXO_DESTINO_FINAL_PUBLICO  IN_LIXO_DESCARTA_OUTRA_AREA  IN_LIXO_JOGA_OUTRA_AREA  IN_LIXO_OUTROS  IN_LIXO_RECICLA  IN_TRATAMENTO_LIXO_SEPARACAO  IN_TRATAMENTO_LIXO_REUTILIZA  IN_TRATAMENTO_LIXO_RECICLAGEM  IN_TRATAMENTO_LIXO_INEXISTENTE  IN_ALMOXARIFADO  IN_AREA_VERDE  IN_AUDITORIO  IN_BANHEIRO_FORA_PREDIO  IN_BANHEIRO_DENTRO_PREDIO  IN_BANHEIRO  IN_BANHEIRO_EI  IN_BANHEIRO_PNE  IN_BANHEIRO_FUNCIONARIOS  IN_BANHEIRO_CHUVEIRO  IN_BERCARIO  IN_BIBLIOTECA  IN_BIBLIOTECA_SALA_LEITURA  IN_COZINHA  IN_DESPENSA  IN_DORMITORIO_ALUNO  IN_DORMITORIO_PROFESSOR  IN_LABORATORIO_CIENCIAS  IN_LABORATORIO_INFORMATICA  IN_PATIO_COBERTO  IN_PATIO_DESCOBERTO  IN_PARQUE_INFANTIL  IN_PISCINA  IN_QUADRA_ESPORTES  IN_QUADRA_ESPORTES_COBERTA  IN_QUADRA_ESPORTES_DESCOBERTA  IN_REFEITORIO  IN_SALA_ATELIE_ARTES  IN_SALA_MUSICA_CORAL  IN_SALA_ESTUDIO_DANCA  IN_SALA_MULTIUSO  IN_SALA_DIRETORIA  IN_SALA_LEITURA  IN_SALA_PROFESSOR  IN_SALA_REPOUSO_ALUNO  IN_SECRETARIA  IN_SALA_ATENDIMENTO_ESPECIAL  IN_TERREIRAO  IN_VIVEIRO  IN_DEPENDENCIAS_PNE  IN_LAVANDERIA  IN_DEPENDENCIAS_OUTRAS  IN_ACESSIBILIDADE_CORRIMAO  IN_ACESSIBILIDADE_ELEVADOR  IN_ACESSIBILIDADE_PISOS_TATEIS  IN_ACESSIBILIDADE_VAO_LIVRE  IN_ACESSIBILIDADE_RAMPAS  IN_ACESSIBILIDADE_SINAL_SONORO  IN_ACESSIBILIDADE_SINAL_TATIL  IN_ACESSIBILIDADE_SINAL_VISUAL  IN_ACESSIBILIDADE_INEXISTENTE  QT_SALAS_EXISTENTES  QT_SALAS_UTILIZADAS_DENTRO  QT_SALAS_UTILIZADAS_FORA  QT_SALAS_UTILIZADAS  QT_SALAS_UTILIZA_CLIMATIZADAS  QT_SALAS_UTILIZADAS_ACESSIVEIS  IN_EQUIP_PARABOLICA  IN_COMPUTADOR  IN_EQUIP_COPIADORA  IN_EQUIP_IMPRESSORA  IN_EQUIP_IMPRESSORA_MULT  IN_EQUIP_SCANNER  IN_EQUIP_NENHUM  IN_EQUIP_DVD  QT_EQUIP_DVD  IN_EQUIP_SOM  QT_EQUIP_SOM  IN_EQUIP_TV  QT_EQUIP_TV  IN_EQUIP_LOUSA_DIGITAL  QT_EQUIP_LOUSA_DIGITAL  IN_EQUIP_MULTIMIDIA  QT_EQUIP_MULTIMIDIA  IN_EQUIP_VIDEOCASSETE  IN_EQUIP_RETROPROJETOR  IN_EQUIP_FAX  IN_EQUIP_FOTO  QT_EQUIP_VIDEOCASSETE  QT_EQUIP_PARABOLICA  QT_EQUIP_COPIADORA  QT_EQUIP_RETROPROJETOR  QT_EQUIP_IMPRESSORA  QT_EQUIP_IMPRESSORA_MULT  QT_EQUIP_FAX  QT_EQUIP_FOTO  QT_COMP_ALUNO  IN_DESKTOP_ALUNO  QT_DESKTOP_ALUNO  IN_COMP_PORTATIL_ALUNO  QT_COMP_PORTATIL_ALUNO  IN_TABLET_ALUNO  QT_TABLET_ALUNO  QT_COMPUTADOR  QT_COMP_ADMINISTRATIVO  IN_INTERNET  IN_INTERNET_ALUNOS  